name: lumo_loader
description: Beautiful, modern, and highly customizable Flutter loading animations with smooth and lightweight performance.
version: 1.0.1

homepage: https://github.com/mehkaarrana/lumo_loader
repository: https://github.com/mehkaarrana/lumo_loader
issue_tracker: https://github.com/mehkaarrana/lumo_loader/issues

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.10.0"

topics:
  - flutter
  - loader
  - loading
  - animation
  - spinner

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: